### ISSUE TITLE
Create a generic Field block to display and edit post meta data

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/sb-field-block#1]
### Requirements
- A generic block to display the value of post meta field
- Optionally to display the field's description 
- Optionally, to allow the value to be edited and saved

### Proposed solution
- Use an attribute which accesses post meta data
- Dynamically alter the attribute's fields to refer to the chosen field
- Use the REST API to determine which fields can be displayed

```
attributes: {
		seenBefore: {
			type: 'string',
			source: 'meta',
			meta: '_seen_before'
		},
	},
```

**Note:** I don't yet know how to dynamically alter an attribute's fields, 
nor do I know how to obtain each field's properties from the REST results.

**Note:** Even though I purchased ACF Pro in 2019, I've never been an ACF user. 
I'm going to develop the block with server side rendering using oik-fields functionality.
If this can be extended to work with other methods of defining post meta data then that's a bonus. 

### Background to the requirement / proposed solution

In oik-blocks, the Fields block ( oik-block/fields ) is a Server Side Rendered block that displays post meta data and virtual information about a post.  See https://www.oik-plugins.com/block/fields-oik-block-fields/
When the display option is All, it displays the values of all of the Fields associated with the post, including Taxonomy terms and virtual fields. 

In order to display an individual field I still need to use a shortcode:
- `[bw_fields _field_name]` to display a field with a label
- `[bw_field _field_name]` to display a field without a label

An example is the `home-body.html` post template part in SB.

Here's the progression of development of the _Seen before_ field.   
```
[bw_field _seen_before]
[bw_fields _seen_before]
<!-- wp:oiksb/sb-field-block /-->
<!-- wp:bigram/seen-before /-->
```
Example result displayed:
```
1108
Seen before: 1108
Seen before:1,107 times
Seen before:1,108 times
```

The `_seen_before` field is now delivered as the `bigram/seen-before` block.
And Yes! I can explain why the value is 1107 in one place and 1108 elsewhere.
It's to do with the order of execution; blocks are expanded before shortcodes. 

1. oiksb/sb-field-block - increments the post meta value
2. bigram/seen-before - also increments the post meta value
3. bw_field just displays the current value
4. bw_fields just displays the current value

Also from `home-body.html`, copied from Fizzie's `metadates.html` this uses `[bw_field]` since we're displaying properties of the post, rather than post meta.

```
<p>Published: [bw_field post_date] | Last updated: [bw_field post_modified] [post-edit]</p>
```
The `[post-edit]` shortcode is another candidate for a separate block.

Using shortcodes still has some advantages. 
1. They can be typed **inline** in paragraph blocks
2. They don't need additional block development

Dynamic blocks have pros and cons relative to shortcodes

- If a dynamic block is not supported then nothing is displayed.
- If a shortcode is not supported then the unexpanded shortcode is displayed.

Whether not it's a pro or a con depends on your viewpoint.

Given that the way forward is to use blocks, block templates or block patterns and to eventually eliminate meta boxes
it makes sense to attempt to develop a generic field block that can be used to display and edit post meta data.

**Comment by bobbingwide** [comment]
> Note: I don't yet know how to 
obtain each field's properties from the REST results.

But I do know that the data is available in response to `wp-json/v2/`

https://github.com/bobbingwide/bigram/issues/23#issuecomment-808876903

**Comment by bobbingwide** [comment]
I copied the relevant part of the comment below

The meta data that has been registered is available in the REST API output.

URL | What you can see
---- | -----------------
wp-json/v2/ | The properties for each meta data field associated with each post type
wp-json/v2/bigram | The actual value(s) for the meta data
wp-json/v2/bigram/ID | The actual value(s) for the meta data

Property definitions

![image](https://user-images.githubusercontent.com/2474435/112748989-69b21e00-8fb7-11eb-9188-c1c441b05024.png)


Value for post
![image](https://user-images.githubusercontent.com/2474435/112749071-d62d1d00-8fb7-11eb-8479-8707cf918bf6.png)

**Comment by bobbingwide** [comment]
I tried using
```
function getMetaFieldsAlt() {
	wp.apiFetch( { path: '/wp/v2',} )
		.then( data => {
		console.log( 'response:', data );
		}
	);
} 
```
to get this data but, unless I'm reading it incorrectly, the data that was visible when using `/wp-json/wp/v2` in the browser is not in `data`.  This doesn't make much sense to me.

I also note that this information is already being passed back to the browser in the editor. 
It's in the `$preload_data` returned to the editor as the parameter to `wp.apiFetch.use( wp.apiFetch.createPreloadingMiddleware()` 

So how do I get access to it myself?

**Comment by bobbingwide** [comment]
> Note: I don't yet know how to dynamically alter an attribute's fields,

I asked these questions in #core-editor ( https://wordpress.slack.com/archives/C02QB2JS7/p1616951678463900 )

> Can anyone point me to code in Gutenberg source that uses `wp-json/wp/v2` to get access to the properties of meta fields for each post type?  And perhaps some other code that will enable me to change the properties for an attribute with source: meta . Better still some documentation. Pretty please.

I got answers from Timothy Jacobs. He convinced me that since I was using `setMeta` I didn't need to have used an attribute to display the current value.  This is the relevant code.

```
const [ meta, setMeta ] = useEntityProp(
		'postType',
		postType,
		'meta'
	);
	const metaFieldValue = meta['_seen_before'];
	function updateMetaValue( newValue ) {
		setMeta( { ...meta, '_seen_before': newValue } );
	}
```

So in the `return` I can replace `{attributes.seenBefore}` with `{metaFieldValue}`.
Therefore, I don't need to be able to change the `seenBefore` attributes `meta` value to refer to a different post meta key
I just need to change the hardcoded value in 
```
const metaFieldValue = meta['_seen_before'];
	function updateMetaValue( newValue ) {
		setMeta( { ...meta, '_seen_before': newValue } );
	}
```
to be the attribute which will contain the name of the field being displayed.

**Comment by bobbingwide** [comment]
With regards to loading the mapping of field names to the description
eg `{ name: '_seen_before', value: 'Seen before' }`
the REST request to perform uses the `OPTIONS` method.
This, I believe, is what _discovery_ is all about.

My original code was something like this.
``` 
function getMetaFieldsAlt() {
	wp.apiFetch( { path: '/wp/v2/posts', 'method': 'OPTIONS'} )
		.then( data => {
		console.log( 'response:', data );
		var properties = data['endpoints'][1]['args']['meta']['properties'];
		console.log( properties );
		var propertyNames = Object.getOwnPropertyNames( properties);
		console.log( propertyNames );
		}
	);
}
```

Had I continued to use `/wp/v2` then the data would have been differently structured.
Extracting the properties would have been something like this.
```
//var routes = data['routes'];
//var post_route = data['routes']['/wp/v2/posts'];
// var properties = post_route['endpoints'][1]['args']['meta']['properties'];
```

**Comment by bobbingwide** [comment]
Update to the requirements and proposed solution.

### Requirements
1. Need an initial display to choose the post type then the field.
2. Once chosen the block should not need to list the fields.
3. Unless the user wants to change the field name
4. We have to cater for fields which don't have a description
5. And fields which aren't post meta fields, such as taxonomies
6. We need to cater for multi select fields
7. And fields which aren't actually strings - eg serialised fields

### Proposed solution - for this _sprint_
- [ ] Implement the server rendering for the front end
- [ ] Add input fields for postType and fieldName as overrides to the selection list
- [ ] Add a post type selection list ( see oik-block/content )
- [ ] Improve the loading of the lists

**Comment by bobbingwide** [comment]
It didn’t take me long to realise how little you can actually achieve if you only know the meta key or name for a field. The REST API provides the `Description`, the data type ( string, numeric or Boolean) and whether or not the field is single but not much else to explain how to validate or display the value.  

The difficult challenges are not going to be resolved by a plugin agnostic solution

1. How to cater for the different field types? Eg 
2. What to do with post meta boxes? How to synchronise data?

**Comment by bobbingwide** [comment]
> 2. What to do with post meta boxes? How to synchronise data?

Assuming we can detect field block in the post content when the post is opened for editing, it should be possible to disable meta boxes that would otherwise duplicate the editing capability for post meta data.  

This assumption is based on the fact that post meta boxes can be registered with a couple of options
In oik-block I recently used `__back_compat_meta_box`. 

```
add_meta_box( 'oik_block', __( "Editor selection", 'oik-block' ), 'oik_block_meta_box', $post_type, 'normal', 'default',
        [ '__back_compat_meta_box' => true ]
        );
```
Setting it to true means that the meta box is only used in the Classic editor.
The alternative is to set `__block_editor_compatible_meta_box` to false.
See https://github.com/bobbingwide/oik-block/issues/18#issuecomment-859396234

The further assumption is that the meta box's registration can be amended at run time, just prior to the editor attempting to display it.

**Comment by bobbingwide** [comment]
> The difficult challenges are not going to be resolved by a plugin agnostic solution. 
How to cater for the different field types? 

- The oik plugin provides functions in `includes\bw_register.php` to register fields and associate them to post types.
- `bw_register_field()`, the field registration function, defines the field name, field type, field title and an args array containing options for the field.
-`bw_register_field_for_object_type()` allows the field to be defined for use by the REST API, using `register_post_meta()`, which uses `register_meta()`.  
- The WordPress REST API has no knowledge of the mechanism used to present the data.

**Comment by bobbingwide** [comment]
I've implemented a first pass at a REST endpoint to return information about fields.  `wp-json/oiksb/v1/fields`
It returns an array of post type to field mappings where the field is registered using `register_post_meta()` as well as an oik-field.
Note: For oik-fields this is done by adding `true` as the third parameter.
```
bw_register_field_for_object_type( $field_name, $post_type, true );
```
This is an optional parameter which defaults to `false`.

In the screen capture below we can see the details for the `_oik_type` and `_oik_slug` fields registered against the `oik-plugins` post type. 
The JSON structure is **experimental** and will need tweaking once some JavaScript code has been written to consume it.
 
![image](https://user-images.githubusercontent.com/2474435/122671869-89c13a00-d1c0-11eb-8b4a-c4cdcc21cccb.png)

**Comment by bobbingwide** [comment]
Interestingly, I didn't see this PHP Notice until recently. 

"PHP Notice:  register_rest_route was called <strong>incorrectly</strong>. The REST API route definition for <code>oiksb/v1/fields</code> is missing the required <code>permission_callback</code> argument. For REST API routes that are intended to be public, use <code>__return_true</code> as the permission callback. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.5.0.) in C:\apache\htdocs\wordpress\wp-includes\functions.php on line 5458"

**Comment by bobbingwide** [comment]
> once some JavaScript code has been written to consume it.

I'm now trying to change the JavaScript to use the data returned from `oiksb/v1/fields`.

Challenges are:
1. REST request being triggered multiple times.
2. Not having a good example to follow.

I believe I've read these before
- https://awhitepixel.com/blog/create-and-fetch-custom-rest-endpoints-in-gutenberg-blocks/
- https://wholesomecode.ltd/blog/wordpress-gutenberg-rest-api/

what's really frustrating is not being able to find documentation in wordpress.org
I did however find a typo for which I developed a PR.

**Comment by bobbingwide** [comment]
It appears to me that, when working in the context of  `post-template` ( was `query-loop`),  in order to choose the field to be displayed I will need to be able to select from a list of post-types first, then list the fields associated with the post type.

There needs to be logic to render a post type select list, then logic to render the field select list, given the post type.
I believe I need to change my original code in `Fields.js` to implement a **data store** that can be used for both the PostType select list and the Fields select list. 

I believe I need to understand how to use the data store ( `registerStore`), which means understanding the concepts of Redux.
The documentation in https://developer.wordpress.org/block-editor/reference-guides/packages/packages-data-controls/
and https://developer.wordpress.org/block-editor/reference-guides/packages/packages-data/
helps a bit. 
But https://developer.wordpress.org/block-editor/reference-guides/packages/packages-redux-routine/ currently means nothing to me. Try reading the Motivation section. Let's hope I won't have to use it.

**Comment by bobbingwide** [comment]
For the PostType select list I can try to use `oik-content/post_type.js` from `oik-blocks`.
And pass the chosen post_type to the Fields component.
It may also be necessary to use the `SelectTextControlCombo.js` to allow overrides to the Post Type and Field Name select lists.

**Comment by bobbingwide** [comment]
Plugins which use `registerStore` include:
- gutenberg
- Editors Kit ( block-options )
- GhostKit 
- gt-blocks
- gutenbee
- boxer-block
- newspack blocks
- full-site-editing
- snow-monkey-blocks
- ultimate-addons-for-gutenberg
- woo-gutenberg-products-block
- woocommerce
- wordpress-seo 

This list includes plugins where `registerStore` was found in the build folders; for plugins where I didn't have the source.

Gutenberg references createReduxStore quite a lot.

**Comment by bobbingwide** [comment]
Now I'm reading Darren Ethier's "A Practical Overview of the @wordpress/data API" https://unfoldingneurons.com/2020/wordpress-data-interfacing-with-the-store

**Comment by bobbingwide** [comment]
I've changed the structure of the REST response from `https://s.b/wordpress/wp-json/oiksb/v1/fields` to return
objects which are easier to filter. 

![image](https://user-images.githubusercontent.com/2474435/123771576-10fa6600-d8c3-11eb-8371-380d06925a32.png)

For each post type where there are fields there's an object with `postType` and `fields` keys.
The `fields` structure is an array of objects for each field with `name`, `#field_type`, `#title` and `#args` keys.

`#args` is a sparsely populated object. It may be null.

This should make it easier to: 
- filter the data to return the fields for the selected post type 
- and to build the select list of fields from which to choose.

**Comment by bobbingwide** [comment]
> The [post-edit] shortcode is another candidate for a separate block.

See https://github.com/bobbingwide/sb-post-edit-block

**Comment by bobbingwide** [comment]
### Current status
- I've managed to use the the REST API to access `/oiksb/v1/fields`
- and stored the data in a custom store `oiksb/fields`
- and been able to get the list of fields for a particular post type ( currently hardcoded as `oik-plugins` ) 
- and seen the results displayed in the front end using server side rendering
- even though the block crashes in the editor
- 
```
<!-- wp:oiksb/sb-field-block {"fieldName":"_oikp_type"} /-->
<!-- wp:oiksb/sb-field-block {"fieldName":"_oikp_slug"} /-->
```

Now I need to revisit the requirements to define what the block is supposed to do. 

### Long term requirements

By delivering a new interface for displaying and editing (and even defining?) post meta fields, to eventually replace:
- `[bw_field]` and `[bw_fields]` shortcodes provided by oik-fields
- and the **Fields** meta box provided by oik in `includes\bw_metadata.php`

Additionally
- To support the display of fields registered using ACF
- To support fields associated with post types, taxonomies and users

### Immediate requirements

- [ ] Ability to choose the field to display.
- [ ] Ability to use context provided by the query block
- [ ] Server Side Rendered field display within the editor and on the front end
- [ ] Possibility to edit the simpler text based fields in the editor.


### Proposed solution

Logic to set the attributes to determine the field to display.

postType | Processing
---------  | --------------
null  | Display Post type selection list, defaulting to current post type
set | Display current value and toggle to override
invalid | Display Post type selection list, defaulting to current post type.

> For the PostType select list I can try to use `oik-content/post_type.js` from oik-blocks.

I'll copy and cobble the logic to implement the solution that makes use of `useSelect`; same as `field.js`

field | Processing
----- | ------------
null | Display Field selection list, if post type chosen
set | Display current value and toggle to override
invalid | Display Field selection list, if post type chosen

I don't yet know the best way to display the Selection information in the block.
Perhaps I should watch the relevant session from WordCamp Europe.

**Comment by bobbingwide** [comment]
I've raised #2 to separate out the logic to allow the post meta data to be edited.
Now I need to raise another issue to allow the post meta data to be displayed.

**Comment by bobbingwide** [comment]
I've not closed this since there are a number of tasks that have not been addressed.
